name: Deploy addons to VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}
          script: |
            TARGET_PATH=/root/libya/dev-18/addons/dev/ics_tour_management

            git config --global --add safe.directory $TARGET_PATH

            cd $TARGET_PATH
            git fetch --all
            git reset --hard origin/dev   # ✅ Correction ici

            docker restart dev-18-odoo18-1

            echo "✅ Deployment completed for branch dev"
