name: Deploy addons to VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}        
          script: |
            git config --global --add safe.directory /home/user/odoo-18-docker-compose/addons
            cd /home/user/odoo-18-docker-compose/addons
            git pull origin main
            docker restart odoo-18-docker-compose-odoo18-1
