name: Deploy addons to VPS

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy on VPS via SSH
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          port: ${{ secrets.VPS_PORT }}        
          script: |
            git config --global --add safe.directory /root/libya/dev-18/addons/dev
            cd /root/libya/dev-18/addons/dev
            git pull origin dev
            docker restart dev-18-odoo18-1
